### PR TITLE
Improve

### PR DESCRIPTION
**Pull request by ghost**
Hi ! 
I was looking for a dmenu script to handle mocp and I found yours. I made some changes.

### CODE REVIEW

**Comment by zordsdavini** [comment]
You can add yorself to contributors list

**Comment by ghost** [comment]
How can I do that ? (This is my first pull request :tada:)

**Comment by zordsdavini** [comment]
Just after 4th line add your name and year as comment. Nice job :+1:

**Comment by ghost** [comment]
Done !

**Comment by ghost** [comment]
A little problem I hadn't thought of. If the playlist is very large, dmenu will extend beyond the screen.

(By the way, which patch does option "-h" come from ?)

**Comment by zordsdavini** [comment]
-l 50 displays only 50 lines. I use dmenu2 in archlinux, it has -h option. Maybe all dmenu options should go into script argument and user can adjust how it should look or add -h option. Nice job. Thanks

**Comment by ghost** [comment]
Indeed, it may be good. Otherwise, the user will modify the options he wants to add himself. Thanks !

**Pull request merged**
